--test data 
--Spring Boot Auto Configuration ensures that this data is loaded up when application starts up.

insert into CONVERSION_VALUE(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10001,'GBP','GB',1.29);
insert into CONVERSION_VALUE(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10002,'INR','IND',0.014);
insert into CONVERSION_VALUE(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10003,'EUR','ANDORRA',1.11);
insert into CONVERSION_VALUE(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10004,'PAR','pakistan',0.0064);
insert into CONVERSION_VALUE(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10005,'NZD','new zealand',0.64);


insert into CONVERT_CURRENCY(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10001,'GBP','GB',1.29);
insert into CONVERT_CURRENCY(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10002,'INR','IND',0.014);
insert into CONVERT_CURRENCY(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10003,'EUR','ANDORRA',1.11);
insert into CONVERT_CURRENCY(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10004,'PAR','pakistan',0.0064);
insert into CONVERT_CURRENCY(id,CURRENCY_CODE,COUNTRY,CONVERSION_FACTOR)
values(10005,'NZD','new zealand',0.64);